### ISSUE TITLE
installation error (pybedtools)

### ISSUE THREAD

**Issue by jklvrt** [aertslab/scenicplus#235]
unfortunately had to reinstall ubuntu because of a glitchy update, and now need to reinstall scenic+...
got it to work on last installation, but now the pip install step (in a fresh scenicplus conda environment) exits with the following error (error 1).
seems to be an issue with pybedtools specifically, and installing that separately via conda does not work (pybedtools doesn't seem to work on python 3.8; error 2). thanks in advance for any ideas/suggestions

**Error 1:**

     cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from pybedtools/include/bedFile.h:16,
                       from pybedtools/cbedtools.cpp:802:
      pybedtools/include/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
         35 | #include <zlib.h>
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybedtools
  Running setup.py clean for pybedtools
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /tmp/pip-install-pqx7wnq1/pybedtools_954a1f3246eb43be8febb8ae2a5dfcf2/setup.py:55: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      /home/jonathan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'language_level'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: option --all not recognized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pybedtools
Successfully built loomxpy pyscenic pycistarget pycisTopic
Failed to build pybedtools
ERROR: Could not build wheels for pybedtools, which is required to install pyproject.toml-based projects

**Error 2:**

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pybedtools -> python[version='>=3.11,<3.12.0a0|>=3.7.1,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - pybedtools -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35

**Comment by SeppeDeWinter** [comment]
Hi @jklvrt 

You need to install the development files for zlib, see: https://stackoverflow.com/questions/36374267/how-to-fix-fatal-error-zlib-h-no-such-file-or-directory

Best,

Seppe

**Comment by jklvrt** [comment]
this solution worked, thanks Seppe!

**Comment by SeppeDeWinter** [comment]
No problem!
